from django.urls import path
from . import views

urlpatterns=[
    path("register/",views.register,name="signup"),
    path("verify/",views.verify_otp,name="verify_otp"),
    path("resend/",views.resend_otp,name="resend_otp"),
    path("login/",views.signin,name="signin"),
    path("home/",views.home_page,name="home"),
    path("forgot-password/",views.forgot_password,name="forgotpswd"),
    path("forgot-password-otp/",views.verify_forgot_otp,name="forgot_password_otp"),
    path("reset-password/",views.reset_password,name="reset_password"),
    path("logout/",views.signout,name="signout"),
    path("landing-page/",views.landing,name="landing_page"),
    path("category/<int:id>/products/",views.products_by_category,name="products_on_category"),
    path("products/",views.list_products,name="all_products"),
    path("products/filter/<int:id>/",views.filterProducts,name="filtering"),
    path("products/filter/",views.filterProducts,name="filtering"),
    path("products/<int:id>/",views.productDetail,name="product_details"),
    path("variant/<int:id>/price/",views.weightFilter,name="weight_price"),
    path("address/add/",views.add_address,name="addAddress"),
    path("address/",views.show_address,name="showAddress"),
    path("profile/",views.show_profile,name="profile"),
    path("profile/edit/",views.edit_profile,name="editProfile"),
    path("profile/verify/",views.email_change_otp,name="emailChangeOtp"),
    path("address/edit/<int:id>/",views.edit_address,name="editAddress"),
    path("address/delete/<int:id>/",views.delete_address,name="deleteAddress"),
    path("cart/add/<int:id>",views.add_to_cart,name="addToCart"),
    path("cart/",views.show_cart,name="showCart"),
    path("cart/delete/<int:id>/",views.remove_from_cart,name="removeItem"),
    path("cart/quantity/<int:id>/",views.update_quantity,name="changeQuantity"),
    path('toggle-wishlist/',views.toggle_wishlist, name='toggleWishlist'),
    path("checkout/",views.checkout,name="checkOut"),
    path("checkout/address",views.add_new_address,name="addNewAddress"),
    path('dashboard/',views.user_dashboard,name="userDasboard"),
    path('update-price/',views.update_total_price,name="codExtra"),
    path("order-success/<int:id>",views.order_placed,name="orderSuccess"),
    path("address-list/",views.list_address,name="selectAddress"),
    path("order-list/",views.orders_list,name="order-list"),
    path("order-detail/<int:id>",views.order_detail,name="orderDetail")
]

