# Generated by Django 5.2.6 on 2025-10-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(choices=[('Published', 'published'), ('Out of stock', 'outofstock'), ('Low stock', 'lowstock')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='status',
            field=models.CharField(choices=[('Published', 'published'), ('Out of stock', 'outofstock'), ('Low stock', 'lowstock')], default='Published', max_length=20),
        ),
    ]
