# Generated by Django 5.2.6 on 2025-10-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_products_status_alter_productvariant_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('minimum_purchase_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('usage_limit', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'flat')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
