# Generated by Django 5.2.6 on 2025-11-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_categoryoffer_productoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='categoryoffer',
            index=models.Index(fields=['is_active', 'end_date'], name='admin_app_c_is_acti_af2b99_idx'),
        ),
        migrations.AddIndex(
            model_name='productoffer',
            index=models.Index(fields=['is_active', 'end_date'], name='admin_app_p_is_acti_1a5141_idx'),
        ),
    ]
