# Generated by Django 5.2.6 on 2025-10-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
