# Generated by Django 5.2.6 on 2025-11-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_categoryoffer_is_active_productoffer_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='name',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='name',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
