# Generated by Django 5.2.6 on 2025-11-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_categoryoffer_name_productoffer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='maximum_discount_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
