# Generated by Django 5.2.6 on 2025-10-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='status',
            field=models.CharField(choices=[('Published', 'published'), ('Out of stock', 'outofstock'), ('Low stock', 'lowstock')], default=0),
        ),
    ]
