from django.urls import path
from . import views

urlpatterns=[
    path("dashboard/",views.admin_dashboard,name="dashboard_home"),
    path("login/",views.admin_login,name="admin_signin"),
    path("category/add/",views.add_category,name="addCategory"),
    path("categories/",views.list_category,name="listCategory"),
    path("category/edit/<int:id>",views.edit_category,name="editCategory"),
    path("category/delete/<int:id>",views.delete_category,name="deleteCategory"),
    path("products/",views.products,name="listProduct"),
    path("product/add/",views.add_products,name="addProduct"),
    path("product/edit/<int:id>",views.edit_product,name="editProduct"),
    path("product/delete/<int:id>",views.soft_delete_product,name="deleteProduct"),
    path("search/",views.search,name="searching"),
    path("search/category",views.searchCategory,name="category_search"),
    path('customers/',views.customer,name="users"),
    path("block-button/<int:id>",views.blockUser,name="blockCustomer"),
    path("logout/",views.signout,name="admin_signout"),
    path("orders/",views.order_list,name="orderList"),
    path("detail/<int:id>/",views.order_detail_page,name="orderDetailView"),
    path("order/return/<int:id>/",views.order_return_request,name="orderAction"),
    path("coupon/add/",views.add_coupon,name="couponAdd"),
    path("coupons/",views.list_coupon,name="couponList"),
    path("coupon/delete/<int:id>/",views.delete_coupon,name="couponDelete"),
    path("offers/",views.all_offers,name="allOffers"),
    path("offer/category/add/",views.add_category_offer,name="addOfferCategory"),
    path("offer/product/add/",views.add_product_offer,name="addOfferProduct"),
    path("offer/category/delete/<int:id>/",views.delete_category_offer,name="deleteOfferCatg"),
    path("offer/product/delete/<int:id>/",views.delete_product_offer,name="deleteOfferPrdct"),
    path("wallet/",views.list_wallet,name="allWallet"),
    path("wallet/<int:id>/",views.wallet_details,name="walletDetail"),
]