# Generated by Django 5.2.6 on 2025-10-27 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_productvariant_status'),
        ('user_app', '0002_wishlist_product_alter_wishlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='admin_app.productvariant'),
        ),
    ]
