# Generated by Django 5.2.6 on 2025-11-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wallet',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('failed', 'failed')], default='failed', max_length=20),
        ),
    ]
