# Generated by Django 5.2.6 on 2025-11-09 07:36

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_orderitem_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_choice', models.CharField(blank=True, choices=[('defective_product', 'Defective Product'), ('wrong_item', 'Wrong Item'), ('other', 'other')], max_length=100, null=True)),
                ('approval_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('refunded', 'Refunded'), ('rejected', 'Rejected')], default='pending', max_length=200, null=True)),
                ('return_reason', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='return_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returnitem', to='user_app.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_return', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
