# Generated by Django 5.2.6 on 2025-11-09 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_orderreturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreturn',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='returnitem', to='user_app.orderitem'),
        ),
    ]
