# Generated by Django 5.2.6 on 2025-11-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_alter_orderreturn_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('order_recieved', 'Order Recieved'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('in Transit', 'In transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('rejected', 'Rejected'), ('payment_pending', 'Payment Pending')], default='pending', max_length=20),
        ),
    ]
