# Generated by Django 5.2.6 on 2025-11-13 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_categoryoffer_name_productoffer_name'),
        ('user_app', '0010_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordercoupon', to='admin_app.coupon'),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_price_before_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
