# Generated by Django 5.2.8 on 2025-11-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='transactionID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
