# Generated by Django 5.2.8 on 2025-11-26 05:05

import user_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_wallettransaction_transactionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transactionID',
            field=models.CharField(default=user_app.models.generate_transactionID, max_length=20, unique=True),
        ),
    ]
