# Generated by Django 5.2.8 on 2025-11-26 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_alter_wallettransaction_transactionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderwallet', to='user_app.orders'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='source',
            field=models.CharField(choices=[('order_debit', 'Debited for order'), ('order_return', 'Refund - Order Returned'), ('order_cancel', 'Refund - Order Cancelled'), ('razorpay', 'Credit through Razoypay'), ('referral', 'Referral Bonus')], default='null', max_length=150),
        ),
    ]
