# Generated by Django 5.2.8 on 2025-11-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_wallettransaction_order_wallettransaction_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('order_recieved', 'Order Recieved'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('in Transit', 'In transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('rejected', 'Rejected'), ('payment_pending', 'Payment Pending')], default='Order Received', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='source',
            field=models.CharField(choices=[('razorpay', 'Credit through Razoypay'), ('referral', 'Referral Bonus'), ('order_debit', 'Debited for order'), ('order_return', 'Refund - Order Returned'), ('order_cancel', 'Refund - Order Cancelled')], default='null', max_length=150),
        ),
    ]
