# Generated by Django 5.2.8 on 2025-11-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0017_alter_orderitem_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='source',
            field=models.CharField(choices=[('order_return', 'Refund - Order Returned'), ('order_debit', 'Debited for order'), ('referral', 'Referral Bonus'), ('order_cancel', 'Refund - Order Cancelled'), ('razorpay', 'Credit through Razoypay')], default='null', max_length=150),
        ),
    ]
