# Generated by Django 5.2.8 on 2025-11-28 13:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_banner'),
        ('user_app', '0018_alter_wallettransaction_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='source',
            field=models.CharField(choices=[('order_return', 'Refund - Order Returned'), ('razorpay', 'Credit through Razoypay'), ('order_cancel', 'Refund - Order Cancelled'), ('referral', 'Referral Bonus'), ('order_debit', 'Debited for order')], default='null', max_length=150),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productreview', to='admin_app.productvariant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
