# Generated by Django 5.2.8 on 2025-11-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0019_alter_wallettransaction_source_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='source',
            field=models.CharField(choices=[('razorpay', 'Credit through Razoypay'), ('referral', 'Referral Bonus'), ('order_cancel', 'Refund - Order Cancelled'), ('order_debit', 'Debited for order'), ('order_return', 'Refund - Order Returned')], default='null', max_length=150),
        ),
    ]
