# Generated by Django 5.2.8 on 2025-11-28 19:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0020_review_title_alter_wallettransaction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='review_image'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='source',
            field=models.CharField(choices=[('order_cancel', 'Refund - Order Cancelled'), ('referral', 'Referral Bonus'), ('order_return', 'Refund - Order Returned'), ('razorpay', 'Credit through Razoypay'), ('order_debit', 'Debited for order')], default='null', max_length=150),
        ),
    ]
