# Generated by Django 5.2.8 on 2025-11-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0021_review_image_alter_wallettransaction_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='source',
            field=models.CharField(choices=[('order_debit', 'Debited for order'), ('razorpay', 'Credit through Razoypay'), ('order_cancel', 'Refund - Order Cancelled'), ('order_return', 'Refund - Order Returned'), ('referral', 'Referral Bonus')], default='null', max_length=150),
        ),
    ]
