# Generated by Django 5.2.8 on 2025-12-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0022_remove_review_title_review_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='source',
            field=models.CharField(choices=[('referral', 'Referral Bonus'), ('razorpay', 'Credit through Razoypay'), ('order_debit', 'Debited for order'), ('order_cancel', 'Refund - Order Cancelled'), ('order_return', 'Refund - Order Returned')], default='null', max_length=150),
        ),
    ]
