# Generated by Django 5.2.8 on 2025-12-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0023_alter_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='source',
            field=models.CharField(choices=[('order_debit', 'Debited for order'), ('referral', 'Referral Bonus'), ('razorpay', 'Credit through Razoypay'), ('order_cancel', 'Refund - Order Cancelled'), ('order_return', 'Refund - Order Returned')], default='null', max_length=150),
        ),
    ]
